### ISSUE TITLE
Layout In which this group is used does not show a preview

### ISSUE THREAD

**Issue by Mr-Ramzan** [addisonElliott/SegmentedButton#15]
I have implemented this library in my project no doubt it is awesome.
But the issue I am facing is the preview of the layout does not show up on android studio. 
Below is the preview while segmented group Code is commented.
![image](https://user-images.githubusercontent.com/36961360/61170505-8c9e6380-a583-11e9-8eb3-3ab4fbf4c2e6.png)
And below is preview while not commented:
![image](https://user-images.githubusercontent.com/36961360/61170518-da1ad080-a583-11e9-92eb-667f35184680.png)
It does not cause any error but really slows down the designing process.
Kindly solve the issue Cheers.

**Comment by addisonElliott** [comment]
I understand your frustrations with it not showing in designer. 

Do you have an example project I can test this out on?

Are there any sort of errors within designer that says the component can't be instantiated?

I've messed around with issues like this before and it can be extremely difficult to fix in designer because there is no "knobs" or adjustable parameters to fix it.

**Comment by addisonElliott** [comment]
But, also try to clear cache in Android Studio, restart your machine and Android studio. 

It may do nothing and all, but I just want to make sure that there's not some relic that is causing issues.

**Comment by Mr-Ramzan** [comment]
I really appreciate your quick response.
I ha e tried makin different projects but no use even the sample provided
by you do not show up on designer preview.

**Comment by Mr-Ramzan** [comment]
As many people suggest on StackOverflow changing SDK version or changing Theme.App.......... to Base.Theme.App.... may work...
no use...

**Comment by addisonElliott** [comment]
Hmm, very odd. The sample project shows up on designer for me (**I think**). Let me do a bit of experimentation and get back to you. Maybe the latest Android SDK is causing issues or something?

**Comment by addisonElliott** [comment]
I've discovered that the sample project is not displaying correctly for me either. I'm assuming some sort of change occurred in Android Studio to cause this because it did work at one point.

The exception I receive is: `java.lang.ClassNotFoundException: codetail.graphics.drawables.LollipopDrawable`. I've been debugging it but haven't had much success. Will keep my progress posted here.

**Comment by Mr-Ramzan** [comment]
Thank You  Mr.Addison I Really appreciate.

**Comment by addisonElliott** [comment]
No problem. I'll start with I can't really get you an ETA for when this will be completed. It's a **very odd and specific** bug since it's a problem with Android Studio itself.

Here's the line of code that "offends" Android Studio: https://github.com/addisonElliott/SegmentedButton/blob/master/library/src/main/java/com/addisonelliott/segmentedbutton/SegmentedButton.java#L1308

Disabling that will make it work. I have **no idea** why it has a problem with this. I might even go the route of creating a brand new `RippleDrawable` class with a new package name to see if that's causing the issue.

**Comment by addisonElliott** [comment]
I've debugged this for quite awhile and I have not the slightest idea what is going on. I submitted a bug report to Google and we'll see what happens.

https://issuetracker.google.com/issues/138310608

**Comment by addisonElliott** [comment]
Was able to resolve this with a workaround, should be fixed in 3.1.5

**Comment by Mr-Ramzan** [comment]
Really Appreciate it as it works like a charm. 
Admire your work Thank you
